cluster_name: node
domain: lab.shortrib.net
remote_ovf_url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.ova
default_password: ENC[AES256_GCM,data:Mqf9abUV8+AoM3l3G93e7L0sVcjBxJQEHA==,iv:CsBpb/63f1v2SJjtZolKqVTuT75GlxtE8V9PcqVnJSY=,tag:Zw6OD8PuUFxu+mTEyhxKyA==,type:str]
ssh:
    authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsWPxOAWaavdJo6Itgp2VXyCeQqAA4thIzuY8uxxTI1 cardno:17 600 602
cluster:
    workers: 2
    kubevip_cidr: 10.26.0.65/28
node:
    cpus: 3
    memory: 4096
    disk_size: 40
vsphere:
    server: vcenter.lab.shortrib.net
    username: terraform@shortrib.local
    password: ENC[AES256_GCM,data:B3c3o+wnjzfmLFWCe0Ha9kwSlQ==,iv:P0byIki1Yl/qDiY5tAWBLuBeqS66eEhd76i7iVnwX2o=,tag:O7J1sPvUXVJR5o72l/RNVA==,type:str]
    datacenter: garage
    cluster: homelab
    host: rye.lab.shortrib.net
    resource_pool: homelab/Resources/kurl
    network: kurl-pg
    datastore: vsanDatastore
    folder: replicated
cloudflare:
    api-key: ENC[AES256_GCM,data:PxHZRNcTP0F8YbQ4nZp5fyNZg1mmcNnX7IM7wCIAytvVkkOWWQ==,iv:7Xa9Ey+YDTFHaakq95YuXJkdy9KDqoOPveQiPIOkOBA=,tag:xoHVqPKhDKg2timKxRNK2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-26T18:31:39Z"
    mac: ENC[AES256_GCM,data:5WbGBtfJNWoLGpPk38gkqGQLl8K1DojuiooyFdmvhH9NaBh+rkQptWgCVuw61KsmVgUWxgFfcOaZ15fY2gJQ1sJ9Q8gjo+lZGnV+9LZt44Ev0Ae4h3ERJzAymALuw2j7xh61bPr5JQCVzlXGhhoZsZM1Qb9ZU/vs7zILlDZo+r8=,iv:xn1rAbYxxnHmtt8pGC1k7BffA2khh+jrsy0xk5VbY1c=,tag:pHxAUf+sFweuvYAf4BMOuw==,type:str]
    pgp:
        - created_at: "2022-12-26T18:31:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9VhhrDDnyi5AQ//dZFNj9HIReJ0hm8fS6iYGW2lzabqhYzldz/MXXXci5HU
            z0ajSOCjJLmN5HnXS/5fNTBKHmtpWftNMoHX6pXa3wZDs09THufZ1PGJ/Zte1ARc
            lZ1hx1m6RoXWrYYjm4oBT33a1jvCrglP/FMNjVX2jt/FvZDpJkDX0tq4rOkchZvj
            zvHDaeHk6l0MtT5r4UdYgCzN06zCsp3pn3og9wjjxXI/Suik3DPNT3sbXc0pD491
            xRherfFmSDg8Okn0tcnJlpREJ/GcD/8nhO/wbjPjquDavsi63OLJF9ZE1VxxpwjZ
            GVse9wZyleB2TlB7V0VjEoBMpEYICd/JnZU3ASdi3AiW9dZCVZMsq8+/bbbusSdj
            eMxJm7JbcFCLEB0AdbskaZazU9tyCJEbM/d5CwCy0XvMR1DmmhnP3NpO2Jg6l1y9
            8WXZoIO0YRFK1Dq7SZ97jNJfKpoASAQ1RsRJYrJxTBq4F9OW7V75NPRCAr9QeXp+
            SiGReghs0eExHrm3M9Xftf9shNkytOpPpLep0cgSYnbIFNIYy7a9TyHz15cUFXBQ
            x8vU4uC1lJnoS9CKgaWW9V0Qmbgzz/FypgzaOuwmLJPL66EMsVXwlnj9wXtR3DFh
            oIIuAehg/VmikiY8gnbV6liQL/UNk5If9yHdm5wlQSGka5cJrVFay2VZFsHvDXvS
            XgEDkAFG1asxwahwFGiccUbt896cfQ0rqfUnLPBlz0owDgF2CmfsWaWY64WuM9Aq
            XVucvUaZVaIlzIhVrEcStC5fzWdKBEHZTHIAv4N2oT7FbR7z77wbdwNejCK2gqA=
            =GTL5
            -----END PGP MESSAGE-----
          fp: FAC1CF820538F4A07C8F4657DAD5DC6A21303194
    encrypted_regex: ^(password|api-key|default_password)$
    version: 3.7.3
